/*Like*/
-- % VARIOS CARACTERES (QUALQUER) OU NENHUM
-- _ APENAS UM CARACTERE (QUALQUER)

/*EMPREGADOS COM 5 OU MAIS CARACTERES NO PRIMEIRO NOME*/
SELECT * FROM EMPREGADO WHERE PRIM_NOME LIKE '_____%';

/*EMPREGADOS QUE SÃO DIRETORES*/
SELECT * FROM EMPREGADO WHERE UPPER(CARGO) LIKE 'DIRETOR%';

/*NULL*/
/*Exibir todos os empregados que NAO tenham gerentes*/
SELECT * FROM EMPREGADO WHERE ID_GERENTE IS NULL;

/*Exibir todos os empregados que tenham gerentes*/
SELECT * FROM EMPREGADO WHERE ID_GERENTE IS NOT NULL;

/*Juncoes*/
SELECT * FROM EMPREGADO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM CLIENTE;

/*Juncao Crusadas*/
SELECT * FROM EMPREGADO CROSS JOIN DEPARTAMENTO;
-- 6 X 3 ==> 18
-- 100000 x 5000 ==> 500000000

/*Juncao Interior*/
SELECT * FROM EMPREGADO INNER JOIN DEPARTAMENTO
ON EMPREGADO.ID_DEPTO = DEPARTAMENTO.ID;

/*ID_EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO*/
SELECT EMPREGADO.ID, ULT_NOME, PRIM_NOME, SALARIO, NOME
FROM EMPREGADO INNER JOIN DEPARTAMENTO
ON EMPREGADO.ID_DEPTO = DEPARTAMENTO.ID;

/*ALIAS DE TABELAS*/
SELECT E.ID, E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", E.SALARIO, D.NOME AS "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID;

/*ID_EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO EMPREGADO COM SALARIO > 7500*/
SELECT E.ID, E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", E.SALARIO, D.NOME AS "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE E.SALARIO > 7500;

/*ID_EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO EMPREGADO COM SALARIO > 7500
E QUE NÃO TRABALHAM EM VENDAS*/
SELECT E.ID, E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", E.SALARIO, D.NOME AS "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE E.SALARIO > 7500 AND UPPER(D.NOME) != 'VENDAS';

/*Juncao com mais de duas tabelas*/
/*NOME DO CLIENTE, NOME DO EMPREGADO, CARGO DO EMPREGADO, NOME DO DEPARTAMENTO*/

SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO, D.NOME AS "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
INNER JOIN CLIENTE C
ON E.ID = C.VENDEDOR;

/*Juncao Exterior*/

/*EXIBIR CLIENTE, NOME DO EMPREGADO E O CARGO*/

-- LEFT
-- RIGHT

SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E RIGHT JOIN CLIENTE C
ON E.ID = C.VENDEDOR;

SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E LEFT JOIN CLIENTE C
ON E.ID = C.VENDEDOR;


SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E LEFT JOIN CLIENTE C
ON E.ID = C.VENDEDOR
WHERE C.NOME IS NULL;

SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E RIGHT JOIN CLIENTE C
ON E.ID = C.VENDEDOR
WHERE E.PRIM_NOME IS NULL;


SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E LEFT JOIN CLIENTE C
ON E.ID = C.VENDEDOR
WHERE C.NOME IS NULL
UNION
SELECT C.NOME AS "CLIENTE", E.PRIM_NOME AS "EMPREGADO" , E.CARGO
FROM EMPREGADO E RIGHT JOIN CLIENTE C
ON E.ID = C.VENDEDOR
WHERE E.PRIM_NOME IS NULL;

/***FUNCOES DE GRUPO***/

-- AVG ==> MEDIA
-- SUM ==> SOMA
-- MAX ==> MAIOR VALOR
-- MIN ==> MENOR VALOR
-- COUNT ==> CONTA OS REGISTROS

SELECT * FROM EMPREGADO;

SELECT TO_CHAR(AVG(SALARIO), '999999D99') FROM EMPREGADO;
SELECT TO_CHAR(SUM(SALARIO), '999999D99') FROM EMPREGADO;

SELECT MAX(SALARIO) FROM EMPREGADO;
SELECT MAX(DT_ADMISSAO) FROM EMPREGADO;
SELECT MAX(PRIM_NOME) FROM EMPREGADO;

SELECT MIN(SALARIO) FROM EMPREGADO;
SELECT MIN(DT_ADMISSAO) FROM EMPREGADO;
SELECT MIN(PRIM_NOME) FROM EMPREGADO;

SELECT COUNT(SALARIO) FROM EMPREGADO;
SELECT COUNT(ID_GERENTE) FROM EMPREGADO;
SELECT COUNT(*) FROM EMPREGADO;

/*A MEDIA SALARIAL DOS DEPARTAMENTOS*/
SELECT ID_DEPTO, TO_CHAR(AVG(SALARIO), '99999.99')
FROM EMPREGADO
GROUP BY ID_DEPTO;

/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS DOS 
* EMPREGADOS DE CADA DEPARTAMENTO E DENTRO DO DEPARTAMENTO PARA CADA CARGO 
*/

SELECT ID_DEPTO, CARGO, COUNT(ID), TO_CHAR(AVG(SALARIO), '99999.99'), SUM(SALARIO)
FROM EMPREGADO 
GROUP BY ID_DEPTO, CARGO;

SELECT TO_CHAR(NOW(), 'DD/MM/YYYY');

SELECT TO_NUMBER('23', '99') + TO_NUMBER('23', '99');
SELECT TO_NUMBER('23', '99');
SELECT TO_DATE('1999/01/01', 'YYYY/MM/DD');

/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS DOS 
* EMPREGADOS DE CADA DEPARTAMENTO E DENTRO DO DEPARTAMENTO PARA CADA CARGO 
* APENAS DOS DEPARTAMENTOS COM MEDIA SALARIAL ACIMA DE 10K
*/
SELECT ID_DEPTO, CARGO, COUNT(ID), TO_CHAR(AVG(SALARIO), '99999.99'), SUM(SALARIO)
FROM EMPREGADO 
GROUP BY ID_DEPTO, CARGO
HAVING AVG(SALARIO) > 10000;

/*
SELECT [COLUNAS]
FROM [TABELAS]
[JOINS] ON [CLAUSULA DE JUNCAO]
WHERE [FILTROS]
GROUP BY [COLUNAS]
HAVING [FILTROS DE GRUPO]
ORDER BY [COLUNAS];
*/

SELECT CARGO, COUNT(CARGO)
FROM EMPREGADO
GROUP BY CARGO;


SELECT D.NOME, E.CARGO, COUNT(E.ID), TO_CHAR(AVG(E.SALARIO), '99999.99'), SUM(E.SALARIO)
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D 
ON E.ID_DEPTO = D.ID
WHERE UPPER(CARGO) LIKE 'DIRETOR%'
GROUP BY D.NOME, CARGO
HAVING AVG(SALARIO) > 19000
ORDER BY D.NOME;

/*Subqueries (SUBCONSULTAS)*/
/*Empregados do departamento de vendas*/
SELECT * FROM EMPREGADO
WHERE ID_DEPTO = 20;

SELECT ID FROM DEPARTAMENTO WHERE UPPER(NOME) = 'VENDAS';

SELECT * FROM EMPREGADO
WHERE ID_DEPTO = (SELECT ID FROM DEPARTAMENTO WHERE UPPER(NOME) = 'VENDAS');

/*Empregados que ganham mais que o salario medio da empresa*/
SELECT * FROM EMPREGADO
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPREGADO);


/*Empregados que ganham salario maiores que todos os vendedores*/
SELECT SALARIO FROM EMPREGADO WHERE UPPER(CARGO) = 'VENDEDOR';

SELECT * FROM EMPREGADO
WHERE SALARIO > ALL (SELECT SALARIO FROM EMPREGADO WHERE UPPER(CARGO) = 'VENDEDOR');

/*Empregados que ganham salarios maiores que algum vendedor*/

SELECT * FROM EMPREGADO
WHERE SALARIO > ANY (SELECT SALARIO FROM EMPREGADO WHERE UPPER(CARGO) = 'VENDEDOR');